//
// "colorlanguages.kts" generated by ChatGPT to provide a colorful table with language translations
//  - it's good at generating markdown content
//
package triath.asciiart

println("| Color | English | Spanish | German | Japanese | French | Latin |\u001B[0m")
println("|-------|---------|---------|--------|----------|--------|-------|")
println("\u001B[31m| Red   | red     | rojo    | rot    | 赤      | rouge  | ruber |\u001B[0m")
println("\u001B[33m| Orange| orange  | naranja | orange | 橙      | orange | aurantium |\u001B[0m")
println("\u001B[93m| Yellow| yellow  | amarillo| gelb   | 黄      | jaune  | flavus |\u001B[0m")
println("\u001B[32m| Green | green   | verde   | grün   | 緑      | vert   | viridis |\u001B[0m")
println("\u001B[34m| Blue  | blue    | azul    | blau   | 青      | bleu   | caeruleus |\u001B[0m")
println("\u001B[35m| Purple| purple  | morado  | lila   | 紫      | violet | purpureus |\u001B[0m")
println("\u001B[37m| White | white   | blanco  | weiß   | 白      | blanc  | albus |\u001B[0m")
println("\u001B[30m| Black | black   | negro   | schwarz| 黒      | noir   | niger |\u001B[0m")

